"""State dataclass for hub-spoke architecture.

This module defines the central state object that gets passed through
the executor's while loop, tracking all intermediate data and control flow.
"""
from dataclasses import dataclass, field
from typing import List


@dataclass
class State:
    """Central state object for hub-spoke architecture.

    The State object is passed through the executor's while loop and
    tracks all intermediate data, agent decisions, and control flow.

    Attributes:
        # Input
        topic: User's topic/question
        user_context: Optional context provided by user (≥300 chars allows skip research)

        # Planner decisions
        use_private: Whether to call Miner for private domain research
        use_web: Whether to call Web for public research
        planner_reason: Planner's reasoning for the decision

        # Research materials (Miner dual-layer output)
        structured_points: Structured talking points for Orchestrator
        raw_voice_clips: Original voice clips for Writer to match style

        # Web research results (Web dual-layer output)
        web_structured_points: Structured information from web search for Orchestrator
        web_raw_quotes: Original quotes from web sources for Writer to cite

        # Writing intermediate products
        outline: Outline generated by Orchestrator (≤800 chars)
        draft: Draft article generated by Writer

        # Quality review and backtracking
        critic_score: Critic evaluation score (0-10)
        critic_reason: Reason for the score
        critic_feedback: Feedback for Writer to address (if not passed)
        iteration_count: Number of rewrite iterations (≤3)

        # System state
        next_step: Next agent to execute ("planner"|"miner"|"web"|"orchestrator"|"writer"|"critic"|"done")
        status: Overall status ("PENDING"|"IN_PROGRESS"|"COMPLETED"|"DEGRADED_OUTPUT"|"ERROR")
    """

    # Input
    topic: str
    user_context: str = ""

    # Planner decisions
    use_private: bool = False
    use_web: bool = False
    planner_reason: str = ""

    # Research materials (Miner dual-layer output)
    structured_points: List[str] = field(default_factory=list)
    raw_voice_clips: List[str] = field(default_factory=list)

    # Web research results (Web dual-layer output)
    web_structured_points: List[str] = field(default_factory=list)
    web_raw_quotes: List[str] = field(default_factory=list)

    # Writing intermediate products
    outline: str = ""
    draft: str = ""

    # Quality review and backtracking
    critic_score: int = 0
    critic_reason: str = ""
    critic_feedback: str = ""
    iteration_count: int = 0

    # System state
    next_step: str = "planner"
    status: str = "PENDING"
